---
name: "Security Lab"

on:
  push:
    branches:
      - main
    paths:
      - "solutions/security-lab/**"
      - "generic/**"
      - ".github/workflows/security-lab.yml"
      - "!**.md"
  pull_request:
    paths:
      - "solutions/security-lab/**"
      - "generic/**"
      - ".github/workflows/security-lab.yml"
      - "!**.md"
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write # For Terraform Docs
  pull-requests: write # For Terraform Docs
  id-token: write # For OpenID Connect

jobs:
  terraform:
    uses: DevSecNinja/github-actions/.github/workflows/reusable-workflow-terraform-ci.yml@main
    with:
      working-directory: ./solutions/security-lab
      use-oid-connect: true
      run-terraform-plan: true
      run-terraform-apply: true
    secrets: inherit
